/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-06-27 01:23:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class test_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!doctype html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\" />\r\n");
      out.write("<meta\r\n");
      out.write("	content=\"user-scalable=no,initial-scale=1,maximum-scale=1,minimum-scale=1,width=device-width\"\r\n");
      out.write("	name=\"viewport\" />\r\n");
      out.write("<title>ì¹´ì¹´ì¤ ì´ëª¨í°ì½ìµ</title>\r\n");
      out.write("<meta property=\"og:title\" content=\"ì¹´ì¹´ì¤ ì´ëª¨í°ì½ìµ\">\r\n");
      out.write("<meta property=\"og:url\" content=\"https://e.kakao.com\">\r\n");
      out.write("<meta property=\"og:image\"\r\n");
      out.write("	content=\"https://mk.kakaocdn.net/dn/emoticon/static/images/webstore/og_tag_20201125.png\">\r\n");
      out.write("<meta property=\"og:image:width\" content=\"1440\" />\r\n");
      out.write("<meta property=\"og:image:height\" content=\"720\" />\r\n");
      out.write("<meta property=\"og:description\"\r\n");
      out.write("	content=\"ì§ê¸ í«í ì¸ê¸° ì´ëª¨í°ì½ë¶í° ìë¡ëì¨ ì ê· ì´ëª¨í°ì½ê¹ì§! ì¸ì ë, ë¬´ìì´ë, ëêµ¬ë í ì¸ë°ë ê³µê°!\" />\r\n");
      out.write("<meta property=\"og:site_name\" content=\"ì´ëª¨í°ì½ìµ\" />\r\n");
      out.write("\r\n");
      out.write("<meta name=\"twitter:card\" content=\"summary\">\r\n");
      out.write("<meta name=\"twitter:title\" content=\"ì¹´ì¹´ì¤ ì´ëª¨í°ì½ìµ\">\r\n");
      out.write("<meta name=\"twitter:url\" content=\"https://e.kakao.com\">\r\n");
      out.write("<meta name=\"twitter:image\"\r\n");
      out.write("	content=\"https://mk.kakaocdn.net/dn/emoticon/static/images/webstore/og_tag_20201125.png\">\r\n");
      out.write("<meta name=\"twitter:description\"\r\n");
      out.write("	content=\"ì§ê¸ í«í ì¸ê¸° ì´ëª¨í°ì½ë¶í° ìë¡ëì¨ ì ê· ì´ëª¨í°ì½ê¹ì§! ì¸ì ë, ë¬´ìì´ë, ëêµ¬ë í ì¸ë°ë ê³µê°!\" />\r\n");
      out.write("<script src=\"//t1.daumcdn.net/tiara/js/v1/tiara.min.js\"></script>\r\n");
      out.write("<link rel=\"shortcut icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"https://t1.kakaocdn.net/estoreweb/favicon/e_16x16.ico\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"https://t1.kakaocdn.net/estoreweb/favicon/e_16x16.ico\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"https://t1.kakaocdn.net/estoreweb/favicon/e_16x16.ico\"\r\n");
      out.write("	sizes=\"16x16\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"https://t1.kakaocdn.net/estoreweb/favicon/e_32x32.ico\"\r\n");
      out.write("	sizes=\"32x32\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"https://t1.kakaocdn.net/estoreweb/favicon/e_64x64.ico\"\r\n");
      out.write("	sizes=\"64x64\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"https://t1.kakaocdn.net/estoreweb/favicon/e_android_72x72.png\"\r\n");
      out.write("	sizes=\"72x72\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"https://t1.kakaocdn.net/estoreweb/favicon/e_android_96x96.png\"\r\n");
      out.write("	sizes=\"96x96\" />\r\n");
      out.write("<link rel=\"icon\" type=\"image/x-icon\"\r\n");
      out.write("	href=\"https://t1.kakaocdn.net/estoreweb/favicon/e_android_144x144.png\"\r\n");
      out.write("	sizes=\"144x144\" />\r\n");
      out.write("<link rel=\"apple-touch-icon\" type=\"image/png\"\r\n");
      out.write("	href=\"https://t1.kakaocdn.net/estoreweb/favicon/e_ios_120x120.png\"\r\n");
      out.write("	sizes=\"120x120\" />\r\n");
      out.write("<link rel=\"apple-touch-icon\" type=\"image/png\"\r\n");
      out.write("	href=\"https://t1.kakaocdn.net/estoreweb/favicon/e_ios_152x152.png\"\r\n");
      out.write("	sizes=\"152x152\" />\r\n");
      out.write("<script async\r\n");
      out.write("	src=\"https://www.googletagmanager.com/gtag/js?id=AW-431600468\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("	window.dataLayer = window.dataLayer || [];\r\n");
      out.write("	function gtag() {\r\n");
      out.write("		dataLayer.push(arguments);\r\n");
      out.write("	}\r\n");
      out.write("	gtag('js', new Date());\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("	<div id=\"kakaoIndex\"\r\n");
      out.write("		style=\"overflow: hidden; position: absolute; left: -9999px; width: 0; height: 1px; margin: 0; padding: 0;\">\r\n");
      out.write("		<a href=\"#dkBody\">ë³¸ë¬¸ ë°ë¡ê°ê¸°</a> <a href=\"#dkGnb\">ë©ë´ ë°ë¡ê°ê¸°</a>\r\n");
      out.write("	</div>\r\n");
      out.write("	<div id=\"root\" style=\"height: 100%;\"></div>\r\n");
      out.write("	<script src=\"/bundle.js\"></script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
