/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-06-22 01:59:02 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.days07;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.util.Cookies;
import com.util.Cookies;

public final class ex02_005fdefault_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("jar:file:/C:/Class/JSPClass/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/jspPro/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/days07/auth.jspf", Long.valueOf(1655862756610L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1655356643006L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.util.Cookies");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// 인증 ( 로그인 )한다면 쿠키이름 ( auth ) 쿠키값 ( 로그인 ID ) 저장
	String cname = "auth";
	String logonID = null;
	
	// com.util.Cookies.java
	// Cookies.java 객체 생성 => 생성자 호출 => cookieMap key, value
	Cookies cookies = new Cookies(request);
	if(  cookies.exists(cname)   ){
		// 로그인 했다 ( 인증 )
		logonID = cookies.getValue(cname);
	}

      out.write("\r\n");
      out.write("<!-- include.jspf 지시자 사용 auth.jspf -->\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>2022. 6. 22. - 오전 10:11:52</title>\r\n");
      out.write("<link rel=\"shortcut icon \"type = \"image/x-icon\" href = \"../images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("  div{\r\n");
      out.write("    border: 1px solid gray;\r\n");
      out.write("    width:300px;\r\n");
      out.write("    height:100px;\r\n");
      out.write("    padding:20px;\r\n");
      out.write("  }\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h3>ex02_default.jsp - 메인 페이지</h3>\r\n");
      out.write("\r\n");

	if(  logonID == null ){
		

      out.write("		\r\n");
      out.write("<div id=\"logon\">\r\n");
      out.write("  <form action=\"ex02_logon.jsp\">\r\n");
      out.write("    아이디 : <input type=\"text\" name=\"id\" value=\"admin\" /><br>\r\n");
      out.write("    비밀번호 : <input type=\"password\" name=\"passwd\" value=\"1234\" /><br>\r\n");
      out.write("    <input type=\"submit\" value=\"로그인\" />\r\n");
      out.write("    <input type=\"button\" value=\"회원가입\" /> \r\n");
      out.write("    \r\n");
      out.write("    <!-- ?error -->\r\n");
      out.write("    ");

    	String error = request.getParameter("error");
    	if ( error != null ){
    
      out.write("\r\n");
      out.write("    <span style=\"color:red\">로그인 실패했습니다.</span>\r\n");
      out.write("    ");
		
    	}
    
      out.write("\r\n");
      out.write("     <script>\r\n");
      out.write("     	$(function(){\r\n");
      out.write("     		$(\"#logon span\").fadeOut(5000);\r\n");
      out.write("     	})\r\n");
      out.write("     </script>\r\n");
      out.write("  </form>\r\n");
      out.write("</div>\r\n");

	}else{


      out.write("\r\n");
      out.write("<div id=\"logout\">\r\n");
      out.write("	[");
      out.print( logonID );
      out.write("]님 환영합니다.<br>\r\n");
      out.write("	<a href=\"ex02_logout.jsp\">로그아웃</a>\r\n");
      out.write("</div>\r\n");

	}

      out.write("		\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 로그인을 하지 않아도 모두가 사용하는 메뉴 -->\r\n");
      out.write("<a href=\"/jspPro/cstvsboard/list.htm\">게시판</a><br>\r\n");
      out.write("<a href=\"#\">공지사항</a><br>\r\n");
      out.write("\r\n");
      out.write("<!-- 반드시 로그인(인증)을 해야지 사용가능한 메뉴 -->\r\n");

	if(  logonID != null){

      out.write("\r\n");
      out.write("<a href=\"#\">일정관리</a><br>\r\n");
      out.write("<a href=\"#\">자료실</a><br>\r\n");
	
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- 인증 + 권한(관리자) -->\r\n");

	if(  logonID != null && logonID.equals("admin")){

      out.write("\r\n");
      out.write("<a href=\"#\">급여관리</a><br>\r\n");
      out.write("<a href=\"#\">사원관리</a><br>\r\n");
		
	}

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
