/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.78
 * Generated at: 2022-06-17 05:31:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.days04;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ex03_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	// 선언문
	// 서블릿 클래스의 멤버변수 ( 필드 ), 메서드 선언
	int age = 20;

	public String getname(){
		return "홍길동";
	}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("<title>2022. 6. 17. - 오후 12:48:28</title>\r\n");
      out.write("<link rel=\"shortcut icon \"type = \"image/x-icon\" href = \"../images/SiSt.ico\">\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<h3>ex03.jsp</h3>\r\n");
      out.write("\r\n");
      out.write("<pre>\r\n");
      out.write("p98 Chapter 04\r\n");
      out.write("1. JSP 요청 ->\r\n");
      out.write("		<- 응답 ( 출력 버퍼 )\r\n");
      out.write("		처리과정\r\n");
      out.write("		\r\n");
      out.write("	브라우저 [ 주소창 : http://~~~/ex01.jsp ]  -> 톰캣 ( 웹서버 + WAS )  -> ex01.jsp\r\n");
      out.write("                                                                                                  jasper     서블릿 클래스\r\n");
      out.write("                                                                                                  ex01_jsp.java\r\n");
      out.write("                                                                                                  \r\n");
      out.write("                                                                                                  \r\n");
      out.write("                                                                                                  ex01_jsp.java\r\n");
      out.write("                                               <- 응답 웹 컨테이너 [ 서블릿 객체 ]\r\n");
      out.write("	\r\n");
      out.write("</pre>\r\n");

	// 스크립트릿
	// jspService(){
	// 지역변수
	String name = "hong";
	// >

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

	// 스크립트릿
	for( int i = 1; i <= 10; i++){
		//out.append( "<li>" + i + "</li>");

      out.write("\r\n");
      out.write("\r\n");
      out.write("	<li>");
      out.print( i );
      out.write("</li>\r\n");
      out.write("\r\n");


	}

      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write(" \r\n");
      out.write("게시판 글 + 첨부 파일\r\n");
      out.write("이클립스 내에서 배포했을 때의 위치 : 첨부파일 업로드\r\n");
      out.write("C:\\Class\\JSPClass\r\n");
      out.write("	\\.metadata\r\n");
      out.write("		\\.plugins\r\n");
      out.write("			\\org.eclipse.wst.server.core\r\n");
      out.write("				\\tmp0\r\n");
      out.write("					\\work\r\n");
      out.write("						\\Catalina\r\n");
      out.write("							\\localhost\\jspPro\\org\\apache\\jsp\\days04\r\n");
      out.write("\r\n");
      out.write("ex03.jsp -> 서블릿 클래스    ->   컴파일 class\r\n");
      out.write("                  ex03_jsp.java     ex03_jsp.class\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("ex03.jsp ->    서블릿 + 서블릿 객체\r\n");
      out.write("\r\n");
      out.write("             <- 응답                    출력버퍼[............]\r\n");
      out.write("[............]\r\n");
      out.write("[............]\r\n");
      out.write("[............]\r\n");
      out.write("[............]\r\n");
      out.write("채워서 보낸다.\r\n");
      out.write(" -->\r\n");


      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
